syntax on
set relativenumber
set number
set cc=80
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set smarttab
set shiftround
set showmatch
set ignorecase
set smartcase
set incsearch
set hlsearch
set wrap
set laststatus=2
set showcmd
set title
set history=1000
set guicursor+=n-v-c:blinkon500-blinkoff500
set backspace=indent,eol,start
set mouse=v
